Update list
system76/firmware-open pull request #247
Opened 2021-09-22 21:03 UTC by ahoneybun

This PR does the following:
- It updates the supported model list to follow this page: https://support.system76.com/articles/open-firmware-systems
as Open Firmware is not on the galp3-c or the darp5.

2021-09-22 21:24 UTC, jacobgkau requested changes
> * Not officially release and not completed code

"Not officially release" is grammatically incorrect, and "not completed code" is very awkward. Try "Not completed or officially released" or just "Unofficial/incomplete".

2021-09-22 21:29 UTC, jacobgkau commented
![image](https://user-images.githubusercontent.com/7199422/134424563-aaf5927c-e46a-4993-904e-2638bc36a0e6.png)

It also looks like the asterisk needs to be escaped, otherwise it shows up as another list entry.

2021-09-22 21:37 UTC, jacobgkau commented
Can I ask why you went beyond the first commit? This list is preceded with `These models are supported` and followed by `Other models may be in development or available without support`, so it seems strange to include unsupported items in the list. I think the only reason these were in the list to begin with was because they were very nearly supported (PRs are still open/work is still ongoing.)

2021-09-22 21:54 UTC, crawfxrd commented
Technically, `README.md.in` is what should be updated. (The last commit to `README.md` would need to be synced as well in that case.)

2021-12-21 20:12 UTC, crawfxrd commented
Done in #260.

2021-12-21 20:12 UTC, closed without merging